language: java
sudo: required
services:
  - docker
  
before_install: 
  - docker build -t kmandati/docker-react -f Dockerfile.dev .
  
deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-533660285542"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"  